package lecture.part2oop

object Exceptions extends App {

  val x: String = null
  println(x.length)

  //throwing and catching


}
